# Generated by Django 6.0.3 on 2026-04-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('auth_token', models.CharField(blank=True, max_length=255)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('success_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('supports_auto_network_detection', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('is_success', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='providers.topupprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
