# Generated by Django 6.0.3 on 2026-04-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupprovider',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
