# Generated by Django 5.2.12 on 2026-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_topupprovider_extra_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupprovider',
            name='daily_cap',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 means unlimited', max_digits=12),
        ),
        migrations.AddField(
            model_name='topupprovider',
            name='supported_networks',
            field=models.CharField(blank=True, help_text='Comma-separated networks such as AWCC,Roshan', max_length=255),
        ),
    ]
