# Generated by Django 5.2.13 on 2026-04-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_topupprovider_daily_cap_and_more'),
        ('shopkeepers', '0003_shop_profile_designer_fields'),
        ('topup', '0004_phase3a_bulk_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuptransaction',
            name='agent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='platform_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='provider_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('default', 'Default'), ('provider', 'Provider'), ('network', 'Network'), ('profile', 'Profile')], default='default', max_length=20)),
                ('network', models.CharField(blank=True, max_length=50)),
                ('agent_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('platform_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='shopkeepers.shopkeeperprofile')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='providers.topupprovider')),
            ],
            options={
                'ordering': ['scope', '-priority', 'name'],
            },
        ),
    ]
