# Generated by Django 6.0.3 on 2026-04-05 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopkeeperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_shop_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shop_name', models.CharField(blank=True, max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('trade_license_number', models.CharField(blank=True, max_length=100)),
                ('tazkira_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_limit_threshold', models.DecimalField(decimal_places=2, default=500, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('tazkira', 'Tazkira'), ('license', 'Trade License'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='shop_documents/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shopkeepers.shopkeeperprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('opening_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receivable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_periods', to='shopkeepers.shopkeeperprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
